# -----------------------------------------------------------------------------
# Output & environment configuration
# -----------------------------------------------------------------------------

SRC_OUT_DIR := generated        # All generated artifacts (go, ts, openapi)
DOC_OUT_DIR := docs             # Your documentation directory
ENV_FILE := .env
PORT := 8765

ifndef BASE_DIR
	BASE_DIR := $(shell pwd)
endif

API_BASE_URL ?= localhost
API_VERSION ?= 0.0.0-dev.$(shell date +%Y%m%d%H%M%S)+$(shell git rev-parse --short HEAD)

# Load environment variables
include $(ENV_FILE)

# Main entry point
all: lint gen-go gen-ts gen-doc


# -----------------------------------------------------------------------------
# Run everything inside the Docker generator image
# Generate everything (protos + SDK + docs)
# -----------------------------------------------------------------------------

all-in-docker: build-docker-image
	@docker run --rm \
		-v $(BASE_DIR):/api \
		-v gopkg_cache:/home/${USER}/go/pkg \
		-v go_cache:/home/${USER}/.cache/go-build \
		-v buf_cache:/home/${USER}/.cache/buf \
		--env BASE_DIR=$(BASE_DIR) \
		livingpackets/livingpacketsapis /bin/sh -c \
			"sudo chown -R ${USER} /home/${USER} && make all"


# -----------------------------------------------------------------------------
# Build Dockerfile that contains protoc, buf and all generators
# -----------------------------------------------------------------------------

build-docker-image:
	@docker build \
		--build-arg UID=$(shell id -u ${USER}) \
		--build-arg USER=${USER} \
		--build-arg PROTOBUF_VERSION=$(PROTOBUF_VERSION) \
		--build-arg PROTOC_GEN_GO_GRPC=$(PROTOC_GEN_GO_GRPC) \
		--build-arg GRPC_GATEWAY_VERSION=$(GRPC_GATEWAY_VERSION) \
		--build-arg BUFBUILD_VERSION=$(BUFBUILD_VERSION) \
		--build-arg SWAGGER_VERSION=$(SWAGGER_VERSION) \
		-t livingpackets/livingpacketsapis .


# -----------------------------------------------------------------------------
# Lint proto files via BUF
# -----------------------------------------------------------------------------

lint:
	@buf lint


# -----------------------------------------------------------------------------
# Generate GO sources (proto + gRPC + gRPC-gateway handlers)
# -----------------------------------------------------------------------------

gen-go:
	@rm -rf ./generated/go
	@buf generate --template buf.gen.go.yaml

	# Initialize a Go module so the generated folder is importable
	@cd generated/go && \
		go mod init github.com/yourorg/yourrepo/generated/go && \
		go mod tidy


# -----------------------------------------------------------------------------
# Generate TypeScript (JS + TS + gRPC-web)
# -----------------------------------------------------------------------------

gen-ts:
	@rm -rf ./generated/ts
	@buf generate --template buf.gen.ts.yaml

	# package.json for NPM publishing
	@export API_VERSION='$(API_VERSION)'; \
		echo '{"name": "@yourorg/protos", "version": "$$API_VERSION"}' \
		| envsubst | jq . > ./generated/ts/package.json

	# Install TS dependencies (grpc-web runtime)
	@cd ./generated/ts && \
		npm install --save \
			google-protobuf \
			@types/google-protobuf \
			@improbable-eng/grpc-web


# -----------------------------------------------------------------------------
# Generate OpenAPI documentation (.swagger.json)
# And build HTML docs through Redocly
# -----------------------------------------------------------------------------

gen-doc:
	@rm -rf ./generated/openapi
	@buf generate --template buf.gen.openapi.yaml

	@echo "Building Redoc documentation…"
	@redoc-cli build \
		-o $(DOC_OUT_DIR)/index.html \
		./generated/openapi/api.swagger.json


# -----------------------------------------------------------------------------
# Serve docs locally using Dockerized nginx
#
# -----------------------------------------------------------------------------

serve-doc-in-docker: all-in-docker
	@docker run --rm -p $(PORT):80 \
		-v $(BASE_DIR)/docs:/usr/share/nginx/html:ro \
		nginx:alpine


# -----------------------------------------------------------------------------
# Tools + dynamic env-file
# -----------------------------------------------------------------------------

EXTRACT_LAST_VERSION := sed 's/^.* \[//;s/\]$$//' | tr ' ' '\n' | grep -v '-' | sort -V | tail -n 1
RUN_GOLANG := run --rm golang:1.23.0-bookworm
GO_LIST := go list -m -versions

env-file:
	@echo '# env for Dockerfile' > $(ENV_FILE)
	@echo '# generated by "make env-file"' >> $(ENV_FILE)

	@echo -n 'PROTOBUF_VERSION=' >> $(ENV_FILE)
	@docker $(RUN_GOLANG) bash -c "$(GO_LIST) google.golang.org/protobuf | $(EXTRACT_LAST_VERSION)" >> $(ENV_FILE)

	@echo -n 'PROTOC_GEN_GO_GRPC=' >> $(ENV_FILE)
	@docker $(RUN_GOLANG) bash -c "$(GO_LIST) google.golang.org/grpc/cmd/protoc-gen-go-grpc | $(EXTRACT_LAST_VERSION)" >> $(ENV_FILE)

	@echo -n 'GRPC_GATEWAY_VERSION=' >> $(ENV_FILE)
	@docker $(RUN_GOLANG) bash -c "$(GO_LIST) github.com/grpc-ecosystem/grpc-gateway/v2 | $(EXTRACT_LAST_VERSION)" >> $(ENV_FILE)

	@echo -n 'BUFBUILD_VERSION=' >> $(ENV_FILE)
	@docker $(RUN_GOLANG) bash -c "$(GO_LIST) github.com/bufbuild/buf | $(EXTRACT_LAST_VERSION)" >> $(ENV_FILE)

	@echo '' >> $(ENV_FILE)
	@echo '# Swagger still locked because of issue 3118' >> $(ENV_FILE)
	@echo 'SWAGGER_VERSION=v0.30.5' >> $(ENV_FILE)
